name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run:  docker build -t vicky-gt/jaytee .

    - name: Push Docker Image
      run: |
        docker tag vicky-gt/jaytee vigneshwargt/jaytee:latest
        docker push vigneshwargt/jaytee:latest

      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
